---
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.pdb.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.pdb.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.pdb.additionalAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.pdb.additionalAnnotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
{{- end }}
