---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.secret.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.secret.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.secret.additionalAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.secret.additionalAnnotations "context" $) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  smtpUsername: "{{ .Values.smtp.username }}"
  smtpPassword: "{{ .Values.smtp.password }}"
  dbUsername: "{{ .Values.externalDatabase.user }}"
  dbPassword: "{{ .Values.externalDatabase.password }}"
  desKey: "{{ include "roundcube.desKey" . }}"
