{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "roundcube.serviceAccountName" . }}
  annotations:
    {{- if .Values.serviceAccount.additionalAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.serviceAccount.additionalAnnotations "context" $) | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.serviceAccount.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value"
    .Values.serviceAccount.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
{{- end }}
